-- Execute no SQL Editor do Supabase quando for ativar o backend do ranking.
create table if not exists public.ranking (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(nome) between 1 and 20),
  tempo_segundos integer not null check (tempo_segundos > 0),
  mortes integer not null default 0 check (mortes >= 0),
  moedas integer not null default 0 check (moedas >= 0),
  final_feito boolean not null default false,
  final_id text not null,
  criado_em timestamptz not null default now()
);

alter table public.ranking enable row level security;

drop policy if exists "Ranking publico pode ser consultado" on public.ranking;
create policy "Ranking publico pode ser consultado"
on public.ranking for select to anon
using (final_feito = true);

drop policy if exists "Partidas concluidas podem ser enviadas" on public.ranking;
create policy "Partidas concluidas podem ser enviadas"
on public.ranking for insert to anon
with check (
  final_feito = true
  and char_length(nome) between 1 and 20
  and tempo_segundos > 0
  and mortes >= 0
  and moedas >= 0
);
