-- Execute no SQL Editor do projeto Supabase usado em frontend/src/services/ranking.js.
create table if not exists public.ranking (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(nome) between 1 and 20),
  personagem_id text check (personagem_id in ('astronaut', 'space-lizard', 'ocstronaut')),
  tempo_segundos integer not null check (tempo_segundos > 0),
  mortes integer not null default 0 check (mortes >= 0),
  moedas integer not null default 0 check (moedas >= 0),
  final_feito boolean not null default false,
  final_id text not null,
  criado_em timestamptz not null default now()
);

-- Atualiza a tabela já existente sem perder os resultados antigos.
alter table public.ranking add column if not exists personagem_id text
  check (personagem_id in ('astronaut', 'space-lizard', 'ocstronaut'));

alter table public.ranking enable row level security;

grant usage on schema public to anon;
grant select, insert on public.ranking to anon;
grant usage on sequence public.ranking_id_seq to anon;

create index if not exists ranking_melhores_idx
on public.ranking (tempo_segundos asc, mortes asc, moedas desc, id asc)
where final_feito = true;

drop policy if exists ranking_select on public.ranking;
create policy ranking_select
on public.ranking for select to anon
using (final_feito = true);

drop policy if exists ranking_insert on public.ranking;
create policy ranking_insert
on public.ranking for insert to anon
with check (
  final_feito = true
  and char_length(nome) between 1 and 20
  and personagem_id in ('astronaut', 'space-lizard', 'ocstronaut')
  and tempo_segundos > 0
  and mortes >= 0
  and moedas >= 0
  and char_length(final_id) between 1 and 32
);
