-- Execute no SQL Editor do projeto Supabase usado em frontend/src/services/ranking.js.
create table if not exists public.ranking (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(nome) between 1 and 20),
  personagem_id text check (personagem_id in ('astronaut', 'space-lizard', 'ocstronaut')),
  tempo_segundos integer not null check (tempo_segundos > 0),
  mortes integer not null default 0 check (mortes >= 0),
  moedas integer not null default 0 check (moedas >= 0),
  final_feito boolean not null default false,
  final_id text not null,
  criado_em timestamptz not null default now()
);

-- Atualiza a tabela já existente sem perder os resultados antigos.
alter table public.ranking add column if not exists personagem_id text
  check (personagem_id in ('astronaut', 'space-lizard', 'ocstronaut'));

-- Para nomes repetidos, preserva a partida mais recente antes de criar a unicidade.
with repetidos as (
  select id, row_number() over (
    partition by upper(btrim(nome)) order by criado_em desc, id desc
  ) as posicao
  from public.ranking
)
delete from public.ranking where id in (select id from repetidos where posicao > 1);

-- O MESMO astronauta pode aparecer uma vez em CADA final (um nick no pódio dos
-- 4 finais), então a unicidade é por nome + final — não mais só por nome.
drop index if exists public.ranking_nome_unico_idx;
create unique index if not exists public.ranking_nome_final_unico_idx
on public.ranking ((upper(btrim(nome))), final_id);

alter table public.ranking enable row level security;

grant usage on schema public to anon;
grant select, insert on public.ranking to anon;

-- A sequência só existe se a coluna identity foi criada neste script. Se a
-- tabela veio de um schema antigo (p. ex. serial), o GRANT falharia e
-- abortaria o script inteiro antes de criar as funções abaixo — por isso o
-- concede de forma condicional (permite reexecutar sobre o projeto atual).
do $$
begin
  if exists (
    select 1 from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'ranking_id_seq'
  ) then
    grant usage on sequence public.ranking_id_seq to anon;
  end if;
end
$$;

create index if not exists ranking_melhores_idx
on public.ranking (tempo_segundos asc, mortes asc, moedas desc, id asc)
where final_feito = true;

drop policy if exists ranking_select on public.ranking;
create policy ranking_select
on public.ranking for select to anon
using (final_feito = true);

drop policy if exists ranking_insert on public.ranking;
create policy ranking_insert
on public.ranking for insert to anon
with check (
  final_feito = true
  and char_length(nome) between 1 and 20
  and personagem_id in ('astronaut', 'space-lizard', 'ocstronaut')
  and tempo_segundos > 0
  and mortes >= 0
  and moedas >= 0
  and char_length(final_id) between 1 and 32
);

-- Faz a substituição atomicamente, sem liberar UPDATE direto na tabela ao visitante.
create or replace function public.salvar_ranking(
  p_nome text, p_personagem_id text, p_tempo_segundos integer,
  p_mortes integer, p_moedas integer, p_final_id text
) returns void
language plpgsql security definer set search_path = ''
as $$
declare
  nome_normalizado text := upper(btrim(p_nome));
begin
  if nome_normalizado is null or char_length(nome_normalizado) not between 1 and 20
     or p_personagem_id is null or p_personagem_id not in ('astronaut', 'space-lizard', 'ocstronaut')
     or p_tempo_segundos is null or p_tempo_segundos <= 0
     or p_mortes is null or p_mortes < 0
     or p_moedas is null or p_moedas < 0
     or p_final_id is null or char_length(p_final_id) not between 1 and 32 then
    raise exception 'Resultado de ranking inválido';
  end if;

insert into public.ranking (nome, personagem_id, tempo_segundos, mortes, moedas, final_feito, final_id)
  values (nome_normalizado, p_personagem_id, p_tempo_segundos, p_mortes, p_moedas, true, p_final_id)
  on conflict ((upper(btrim(nome))), final_id) do update set
    nome = excluded.nome,
    personagem_id = excluded.personagem_id,
    tempo_segundos = excluded.tempo_segundos,
    mortes = excluded.mortes,
    moedas = excluded.moedas,
    final_feito = true,
    final_id = excluded.final_id,
    criado_em = now();
end;
$$;

revoke all on function public.salvar_ranking(text, text, integer, integer, integer, text) from public;
grant execute on function public.salvar_ranking(text, text, integer, integer, integer, text) to anon;

-- Cada partida concluída conta uma única vez, mesmo se o mesmo nome jogar de novo
-- ou se o navegador repetir a requisição ao perder a conexão.
create table if not exists public.finais_concluidos (
  partida_id uuid primary key,
  final_id text not null check (final_id in ('final1', 'final2', 'final3', 'final4')),
  criado_em timestamptz not null default now()
);

create index if not exists finais_concluidos_final_idx on public.finais_concluidos (final_id);
alter table public.finais_concluidos enable row level security;

create or replace function public.registrar_final(p_partida_id uuid, p_final_id text)
returns void
language plpgsql security definer set search_path = ''
as $$
begin
  if p_partida_id is null or p_final_id is null
     or p_final_id not in ('final1', 'final2', 'final3', 'final4') then
    raise exception 'Final inválido';
  end if;

  insert into public.finais_concluidos (partida_id, final_id)
  values (p_partida_id, p_final_id)
  on conflict (partida_id) do nothing;
end;
$$;

revoke all on function public.registrar_final(uuid, text) from public;
grant execute on function public.registrar_final(uuid, text) to anon;

-- RPC de leitura: sempre devolve os quatro finais, inclusive os com zero partidas.
create or replace function public.contagem_finais()
returns table(final_id text, total bigint)
language sql stable security definer set search_path = ''
as $$
  select finais.id, count(registros.partida_id) as total
  from (values ('final1'), ('final2'), ('final3'), ('final4')) as finais(id)
  left join public.finais_concluidos as registros on registros.final_id = finais.id
  group by finais.id
  order by finais.id;
$$;

revoke all on function public.contagem_finais() from public;
grant execute on function public.contagem_finais() to anon;

-- Controles personalizados por astronauta: cada nome tem sua própria config.
-- A leitura é bloqueada para visitantes; só o RPC salvar_controles escreve.
create table if not exists public.controles_jogador (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(nome) between 1 and 20),
  controles jsonb not null default '{}'::jsonb,
  atualizado_em timestamptz not null default now()
);

create unique index if not exists controles_jogador_nome_unico_idx
on public.controles_jogador ((upper(btrim(nome))));

alter table public.controles_jogador enable row level security;
grant select on public.controles_jogador to anon;

-- Concede a sequência apenas se ela existir (tabela criada por este script),
-- senão o GRANT quebraria em projetos recriados com schema antigo.
do $$
begin
  if exists (
    select 1 from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public' and c.relname = 'controles_jogador_id_seq'
  ) then
    grant usage on sequence public.controles_jogador_id_seq to anon;
  end if;
end
$$;

drop policy if exists controles_jogador_select on public.controles_jogador;
create policy controles_jogador_select
on public.controles_jogador for select to anon
using (true);

-- RPC de upsert: cria ou substitui a config do nome (o mesmo nome sobrescreve).
create or replace function public.salvar_controles(p_nome text, p_controles jsonb)
returns void
language plpgsql security definer set search_path = ''
as $$
declare
  nome_normalizado text := upper(btrim(p_nome));
begin
  if nome_normalizado is null or char_length(nome_normalizado) not between 1 and 20 then
    raise exception 'Nome inválido';
  end if;
  if p_controles is null or jsonb_typeof(p_controles) <> 'object' then
    raise exception 'Controles inválidos';
  end if;

  insert into public.controles_jogador (nome, controles, atualizado_em)
  values (nome_normalizado, p_controles, now())
  on conflict ((upper(btrim(nome)))) do update set
    controles = excluded.controles,
    atualizado_em = now();
end;
$$;

revoke all on function public.salvar_controles(text, jsonb) from public;
grant execute on function public.salvar_controles(text, jsonb) to anon;
